name: Re-run Jupyter Notebook on Code Change

on:
  push:
    branches: [ main ]
    paths:
      - '**.ipynb'
      - '**.py'
  pull_request:
    branches: [ main ]
    paths:
      - '**.ipynb'
      - '**.py'

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install jupyter nbconvert wandb scikit-learn matplotlib opencv-python

      - name: Log into Weights & Biases
        run: wandb login ${{ secrets.WANDB_API_KEY }}

      - name: Run Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute distance_classification.ipynb --output distance_classification_out.ipynb
